### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by nsanikitin** [kot-annett/iOS-FakeNFT-StarterProject-Public#29]
**Модуль 1:**
- [x] [Верстка таблицы](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/30)
- [x] [Верстка ячеек](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/31)
- [x] [Показ алерта с ошибкой получения данных о пользователях](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/32)
- [x] [Загрузка списка пользователей с сервера](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/33)

**Модуль 2:**
- [x] [Показ алерта выбора сортировки](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/34)
- [x] [Верстка экрана профиля](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/35)
- [x] [Сортировка пользователей по рейтингу](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/36)
- [x] [Сортировка пользователей по имени](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/37)
- [x] [Сохранение способа сортировки пользователей](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/38)
- [x] [Переход на экран пользователя](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/39)
- [x] [Загрузка информации о пользователе с сервера](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/40)
- [x] [Показ индикатора загрузки при переходе на экран пользователя](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/41)
- [x] [Показ индикатора загрузки при переходе в вебвью на сайт пользователя](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/42)

**Модуль 3:**
- [x] [Верстка экрана коллекции NFT пользователя ](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/43)
- [x] [Переход на вебвью сайта пользователя](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/44)
- [x] [Переход на экран коллекции NFT выбранного пользователя](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/45)
- [x] [Загрузка коллекции NFT с сервера](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/46)
- [x] [Показ индикатора загрузки при переходе на экран коллекции NFT пользователя ](https://github.com/kot-annett/iOS-FakeNFT-StarterProject-Public/issues/47)
